FROM python:2.7
MAINTAINER "Dmitri <dmitri.co>"

RUN apt update && apt-get install -y \
  vim
ENV WORKDIR /workdir/current
RUN mkdir -p $WORKDIR
WORKDIR $WORKDIR

COPY . $WORKDIR
RUN pip install git+git://github.com/Theano/Theano.git #--upgrade --no-deps
RUN pip install git+git://github.com/fchollet/keras.git #--upgrade --no-deps
RUN pip install -r requirements.txt
